# Generated by Django 4.0.3 on 2022-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
